---
title: "Welcome to my website!"
output: 
  html_document:
    theme: spacelab
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## I'm Leslie Huang.
***

### What I do

I'm a quantitative political scientist with a focus on data science. I work in Python and R (and occasionally Stata). Most of my research and side projects involve text analysis and NLP -- especially sentiment analysis, topic modelling, and other unsupervised machine learning techniques. I'm interested in data analysis, especially causal inference.

### Who I am

I have a BA, summa cum laude, from Columbia University in political science and English literature. I am currently a political science PhD student at NYU. 

Prior to grad school, I held editorial and managerial roles at a nonprofit (the Foreign Policy Association) and at a book publisher (W. W. Norton).

### Where to find me

* Check out my works in progress on my <a href="https://github.com/leslie-huang">GitHub</a>.

* You can find me on <a href="https://www.linkedin.com/in/huangleslie">LinkedIn</a>.

### What I'm up to

I'm working on a few cool projects right now:

* Exploring a massive dataset of food reviews from Amazon.com with <a href="https://github.com/leslie-huang/cluster-food">k-means clustering in Python</a>.
* Developing an <a href="https://github.com/leslie-huang/twitterNetworkGraphR">R library that scrapes Twitter and uses network graphs to visualize how users are connected</a>, in order to understand how "viral" tweets spread.
* Writing a series of tutorials in R and Python: Check out my latest post about <a href="Python_tutorials/gradientdescent.html">gradient descent and OLS regression</a>.

Check out these works in progress, in addition to my completed projects, in the section below!

# _My projects_
***

I've put together an overview of my projects. Check my <a href="https://github.com/leslie-huang">GitHub</a> for the latest updates!

### Sentiment analysis of FARC-Colombia negotiations

Can sentiment analysis predict whether peace talks will fail or succeed? Do the statements published by either side during peace talks reveal their willingness to negotiate? Using the statements published by the FARC and the Colombian government, I made a dynamic model that estimates whether each side is hardline or conciliatory during the peace negotiations. I also estimate whether sentiment responds to sentiment -- for instance, does a hardline statement predict a hardline response?

For this project, I constructed an original Spanish-language corpus of documents scraped from the official websites of the guerrilla group FARC, the president of Colombia, and the peace negotiators using Python. The main analysis was done in R.

* See the repos <a href="https://github.com/leslie-huang/MA-thesis-analysis">here</a> (for the main analyis) and <a href="https://github.com/leslie-huang/MA-thesis-scrapers">here</a> (for the scrapers).

* See a version of this paper, which was submitted as part of my PhD coursework and was awarded unanimous "high pass" grades, <a href="https://leslie-huang.github.io/MA_paper.pdf">here</a>.

* I am currently working on refactoring this code into an R package (current version is <a href="https://github.com/leslie-huang/MApkg">here</a>).

### NYC restaurant grades visualizer

I built an interactive tool in Python that provides users with efficient visualizations of health inspection grades from the NYC Department of Health. The user can view a restaurant's grades over time and compare that restaurant with others in the same neighborhood or category. The user can also search for the restaurant with the fewest (or most) health code violations in a given neighborhood or category.

* Check out a demo of the program and its visualization options <a href="https://leslie-huang.github.io/restaurant_demo/Using_the_restaurant_grades_visualizer.html">here</a>.

* See the repo <a href="https://github.com/leslie-huang/restaurant-inspection-grades-visualizer">here</a>.

### Topic models of Antarctica

(In progress.) As a research assistant, I am applying unsupervised machine learning techniques to a dataset of documents pertaining to Antarctica. I cleaned and created the dataset in Python. The bulk of my analysis is done using the `stm` package in R, with pre-processing done using `quanteda`. 

(Files not available to public.)

### Twitter network data scraper

(In progress.) I wrote some scripts to scrape information about a Twitter user's followers and those followers' followers, in order to model networks between social media users.

* See the Python repo <a href="https://github.com/leslie-huang/twitter-ssscraper">here</a>, and the R repo <a href="https://github.com/leslie-huang/twitter-scrapeR">here</a>.

* I'm developing my work in R into a <a href="https://github.com/leslie-huang/twitterNetworkGraphR">custom R library for scraping and visualizing n-degree networks</a>.

### Using Naive Bayes-style techniques to estimate Supreme Court ideology

I scraped Supreme Court opinions from 2003-2015 and constructed a novel dataset using Python. I used the "Wordscores" method, which is similar to Naive Bayes classification. Using ideologically extreme "anchor" texts to train the model, I estimated ideological positions for the remaining opinions and constructed aggregate scores for each justice. These machine-coded ideology scores strongly correlated with the scores assigned to the justices by expert coders.

* See the repo <a href="https://github.com/leslie-huang/supreme-court-opinion-wordscores">here</a>.

### K-means clustering of Amazon food reviews

(In progress.) I'm using k-means clustering to explore more than half a million food reviews from Amazon (data from Kaggle).

* See the repo <a href="https://github.com/leslie-huang/cluster-food">here</a>.


### Coalition formation in civil wars

Why do rebel groups fight amongst themselves, in addition to fighting the government they're seeking to overthrow? I use a series of probit regression models to test the relationship between a rebel group's military capacity and its likelihood of forming coalitions with other rebel groups.

* See the repo <a href="https://github.com/leslie-huang/rebel-coalition-formation-replication">here</a>.


# _Tutorials_

***

I'm currently working a set of tutorials on data analysis in R and Python, in addition to introductory materials on NLP/text analysis.

### R

* <a href="R_tutorials/index.html">R tutorials</a>

### Python

* <A href="Python_tutorials/index.html">Python tutorials</a>

*Last updated April 18, 2017*
